@sessionId=sessionId
@id=1

###
POST http://localhost:3000/api/jsonplaceholder/{{sessionId}}/posts
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

title=foo&body=bar&userId=1

###
POST http://localhost:3000/api/jsonplaceholder/{{sessionId}}/posts
Content-type: application/json; charset=UTF-8

{
    "title": "foo",
    "body": "bar",
    "userId": 1
}

###
POST http://localhost:3000/api/jsonplaceholder/{{sessionId}}/posts
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarypWkUVRLeyG4CBXUe

------WebKitFormBoundarypWkUVRLeyG4CBXUe
Content-Disposition: form-data; name="title"

foo
------WebKitFormBoundarypWkUVRLeyG4CBXUe
Content-Disposition: form-data; name="body"

bar
------WebKitFormBoundarypWkUVRLeyG4CBXUe
Content-Disposition: form-data; name="userId"

1
------WebKitFormBoundarypWkUVRLeyG4CBXUe--


###
GET http://localhost:3000/api/jsonplaceholder/{{sessionId}}/posts/{{id}}

###
GET http://localhost:3000/api/jsonplaceholder/{{sessionId}}/posts

###
PATCH http://localhost:3000/api/jsonplaceholder/{{sessionId}}/posts/{{id}}
Content-type: application/json; charset=UTF-8

{
    "title": "foo"
}

###
PUT http://localhost:3000/api/jsonplaceholder/{{sessionId}}/posts/{{id}}
Content-type: application/json; charset=UTF-8

{
    "id": 1,
    "title": "foo",
    "body": "bar",
    "userId": 1
}

###
DELETE http://localhost:3000/api/jsonplaceholder/{{sessionId}}/posts/{{id}}

###
GET http://localhost:3000/api/jsonplaceholder/{{sessionId}}/posts
?userId=1

###
GET http://localhost:3000/api/jsonplaceholder/{{sessionId}}/posts/{{id}}/comments